using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace SistemaRamais.Ramais
{
    public class RamalManager : RamalManagerBase
    {
        //<suite-custom-code-autogenerated>
        public RamalManager(IRamalRepository ramalRepository)
            : base(ramalRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}