using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace SistemaRamais.Ramais
{
    public class Ramal : RamalBase
    {
        //<suite-custom-code-autogenerated>
        protected Ramal()
        {

        }

        public Ramal(Guid id, string numero, string departamento, string responsavel, string email, string telefone)
            : base(id, numero, departamento, responsavel, email, telefone)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}