using System;

namespace SistemaRamais.Ramais
{
    public class Ramal : RamalBase
    {
        //<suite-custom-code-autogenerated>
        protected Ramal()
        {

        }

        public Ramal(Guid id, string nome, string numero, string departamento, string email, string normalizedName, string normalizedEmail)
            : base(id, nome, numero, departamento, email, normalizedName, normalizedEmail)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}